---
title: "Contract Renewal Statement"
output: github_document
---

## Introduction

Empowering others to do "cool things"

- Teaching
  - Help others find what does or does not interest them 
- Scholarly activity
  - How I find my interest
- Service
  - Provide/create spaces where others can explore their interests

## Teaching

- Transition to master-based grading has allowed me to maintain high standards and gives students multiple opportunities to achieve the level of mastery that they are seeking.
- Encourage students to explore on their own. Recently I have realized that many may have never wanted to do this or had experience with self-exploration, so they need additional guidance along this process.
- How can we help students to become self-motivated?
- I am trying to be more intentional in the directions provided to students so details are presented in a concise, clear way; being cautious of the jargon I use and aware of my own blind-spots.

### Classroom management skills

### Preparation and organization

### Communication

### Enthusiasm

### Knowledge

### Evaluation

### Availability

### Intellectual motivation

### Flexibility and resourcefulness in teaching

### Dedication to students


## Scholarly activity

- Working with students on scholarly activity... I am working on developing a general "syllabus" or "contract" to share with students that are interested in working together on projects so that we have clear expectations of each other.
- List ongoing projects and specific areas that students can work with me on my personal site.
- Learning how to prioritize scholarly activities and when to encourage people to reach out to colleagues.

### Activities expected each year

### Activities expected periodically

### Activities that represent areas of significant focus

## Service

### Activities expected each year

### Activities expected periodically

### Activities that represent areas of significant focus

## Appendices


